import Link from "next/link";
import { QuadChainWorkbench } from "@/components/QuadChainWorkbench";
import {
  buildQuadChainCertificate,
  verifyQuadChainCertificate,
  type QuadChainEvidenceObligation,
  type QuadChainSource,
} from "@/lib/quad-chain";
import {
  quadChainArtifactLinks,
  quadChainHeadlineMetrics,
  quadChainRouteMetrics,
  quadChainThesis,
  totalRouteSavings,
} from "@/lib/quad-chain/metrics";
import { buildQuadChainComparison } from "@/lib/quad-chain/workbench";

const sources: QuadChainSource[] = [
  {
    id: "agent_trace",
    kind: "tool_result",
    content: {
      route: "implementer",
      finding: "MissingStateCookieError",
      fix: "SameSite=Lax",
      policy: "Do not disable csrf checks.",
    },
  },
  {
    id: "audit_memory",
    kind: "memory",
    content: {
      requiredConcept: "oauth callback",
      file: "src/auth/sessionCookie.ts:41",
    },
  },
];

const requiredEvidence: QuadChainEvidenceObligation[] = [
  {
    id: "error",
    sourceId: "agent_trace",
    quote: "MissingStateCookieError",
    required: true,
  },
  {
    id: "fix",
    sourceId: "agent_trace",
    quote: "SameSite=Lax",
    required: true,
  },
  {
    id: "policy",
    sourceId: "agent_trace",
    quote: "Do not disable csrf checks.",
    required: true,
  },
];

const compressedContext = [
  "Implementer packet:",
  "The oauth callback failed with MissingStateCookieError.",
  "The smallest safe fix is restoring SameSite=Lax in src/auth/sessionCookie.ts:41.",
  "Do not disable csrf checks.",
].join("\n");

export default function QuadChainPage() {
  const certificate = buildQuadChainCertificate({
    runId: "quadchain_demo",
    producer: "quad.researcher",
    consumer: "quad.implementer",
    compressedContext,
    sources,
    requiredEvidence,
    answerConcepts: ["oauth callback", "SameSite=Lax", "csrf checks"],
    omittedRanges: [
      {
        sourceId: "agent_trace",
        rangeId: "trace_noise",
        reason: "Verbose logs were not needed for the downstream implementer packet.",
        content: { trace: "heartbeat, cache hits, repeated request metadata" },
      },
    ],
    createdAt: "2026-06-20T00:00:00.000Z",
  });
  const verification = verifyQuadChainCertificate(certificate, {
    compressedContext,
    sources,
    requiredEvidence,
  });
  const routeTotals = totalRouteSavings();
  const initialComparison = buildQuadChainComparison({
    prompt: "Audit the oauth signup trace and produce the smallest safe fix.",
    createdAt: "2026-06-20T00:00:00.000Z",
  });

  return (
    <main className="min-h-screen px-4 py-6 text-[var(--ink)] sm:px-6 lg:px-8">
      <div className="mx-auto flex max-w-6xl flex-col gap-6">
        <header className="flex flex-col gap-4 border-b border-edge pb-5 md:flex-row md:items-end md:justify-between">
          <div className="max-w-3xl space-y-3">
            <Link href="/" className="text-sm text-accent hover:text-accent-dark">
              Back to audit
            </Link>
            <p className="font-mono text-xs text-accent-dark">:: quadchain / proof-carrying context ::</p>
            <h1 className="text-4xl font-semibold tracking-tight md:text-6xl">Quadchain</h1>
            <p className="max-w-2xl text-base leading-7 text-muted">{quadChainThesis}</p>
          </div>
          <div className="font-mono text-xs leading-5 text-soft">
            <div>source chain -- compression chain</div>
            <div>proof chain -- anchor chain</div>
            <div>verify before trust</div>
          </div>
        </header>

        <section className="grid gap-3 md:grid-cols-3">
          {quadChainHeadlineMetrics.map((metric) => (
            <div key={metric.label} className="rounded-lg border border-edge bg-panel/80 p-4 shadow-sm">
              <div className="text-sm text-muted">{metric.label}</div>
              <div className="mt-2 text-3xl font-semibold tracking-tight">{metric.value}</div>
              <div className="mt-2 text-sm leading-6 text-soft">{metric.detail}</div>
            </div>
          ))}
        </section>

        <QuadChainWorkbench initial={initialComparison} />

        <section className="grid gap-4 lg:grid-cols-[1.05fr_0.95fr]">
          <div className="rounded-lg border border-edge bg-panel/80 p-4 shadow-sm">
            <div className="flex items-center justify-between gap-3">
              <div>
                <h2 className="text-xl font-semibold">Live trust packet</h2>
                <p className="mt-1 text-sm text-muted">
                  This receipt is generated by the app verifier at render time.
                </p>
              </div>
              <span className="rounded-lg border border-accent/40 bg-accent/10 px-3 py-1 text-sm text-accent-dark">
                {verification.accepted ? "Accepted" : "Rejected"}
              </span>
            </div>

            <dl className="mt-5 grid gap-3 sm:grid-cols-2">
              <ReceiptRow label="Certificate" value={certificate.certificateId} />
              <ReceiptRow label="Handoff" value={certificate.handoffId} />
              <ReceiptRow label="Merkle root" value={certificate.anchorChain.merkleRoot.slice(0, 24)} />
              <ReceiptRow label="Registry receipt" value={certificate.anchorChain.registryReceipt} />
              <ReceiptRow label="Answer readiness" value={String(certificate.proofChain.answerReadinessScore)} />
              <ReceiptRow label="Failures" value={verification.accepted ? "none" : verification.failures.join(", ")} />
            </dl>
          </div>

          <div className="rounded-lg border border-edge bg-panel/80 p-4 shadow-sm">
            <h2 className="text-xl font-semibold">What it protects</h2>
            <div className="mt-4 space-y-3 font-mono text-sm leading-6">
              {requiredEvidence.map((evidence) => (
                <div key={evidence.id} className="rounded-lg border border-edge bg-paper/70 p-3">
                  <div className="text-soft">{evidence.id}</div>
                  <div>{evidence.quote}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="rounded-lg border border-edge bg-panel/80 p-4 shadow-sm">
          <div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between">
            <div>
              <h2 className="text-xl font-semibold">Role routing</h2>
              <p className="mt-1 text-sm text-muted">
                The win is not just smaller packets. Each agent gets the smallest verified packet for its job.
              </p>
            </div>
            <div className="font-mono text-sm text-accent-dark">
              {formatNumber(routeTotals.rawTokens)} raw -&gt; {formatNumber(routeTotals.quadChainTokens)} verified,
              {" "}
              {routeTotals.reduction}% saved
            </div>
          </div>

          <div className="mt-4 overflow-x-auto">
            <table className="w-full min-w-[760px] border-collapse text-left text-sm">
              <thead className="border-b border-edge text-muted">
                <tr>
                  <th className="py-2 pr-4 font-medium">Role</th>
                  <th className="py-2 pr-4 font-medium">Mode</th>
                  <th className="py-2 pr-4 font-medium">Raw</th>
                  <th className="py-2 pr-4 font-medium">Quadchain</th>
                  <th className="py-2 pr-4 font-medium">Saved</th>
                  <th className="py-2 pr-4 font-medium">Evidence</th>
                </tr>
              </thead>
              <tbody>
                {quadChainRouteMetrics.map((route) => (
                  <tr key={route.role} className="border-b border-edge/70">
                    <td className="py-3 pr-4 font-medium">{route.role}</td>
                    <td className="py-3 pr-4 text-muted">{route.mode}</td>
                    <td className="py-3 pr-4 font-mono">{formatNumber(route.rawTokens)}</td>
                    <td className="py-3 pr-4 font-mono">{formatNumber(route.quadChainTokens)}</td>
                    <td className="py-3 pr-4 font-mono">{route.reduction}%</td>
                    <td className="py-3 pr-4 font-mono">{route.evidence}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="grid gap-4 lg:grid-cols-2">
          <div className="rounded-lg border border-edge bg-panel/80 p-4 shadow-sm">
            <h2 className="text-xl font-semibold">Stage line</h2>
            <p className="mt-3 text-sm leading-6 text-muted">
              Quadchain makes agent memory handoffs trustworthy. One agent can compress its work, another agent can
              verify the certificate, and private context stays off-chain while hashes and roots make tampering visible.
            </p>
          </div>
          <div className="rounded-lg border border-edge bg-panel/80 p-4 shadow-sm">
            <h2 className="text-xl font-semibold">Artifact bundle</h2>
            <div className="mt-3 grid gap-2">
              {quadChainArtifactLinks.map((link) => (
                <a
                  key={link.href}
                  href={link.href}
                  className="rounded-lg border border-edge bg-paper/70 p-3 text-sm transition hover:border-accent/50"
                >
                  <span className="font-medium text-accent-dark">{link.label}</span>
                  <span className="ml-2 text-muted">{link.detail}</span>
                </a>
              ))}
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}

function ReceiptRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-edge bg-paper/70 p-3">
      <dt className="text-xs text-muted">{label}</dt>
      <dd className="mt-1 break-all font-mono text-sm text-[var(--ink)]">{value}</dd>
    </div>
  );
}

function formatNumber(value: number): string {
  return value.toLocaleString("en-US");
}
